return {
  'NickJAllen/automator.nvim',
  dev = true,
  cmd = { 'Automator' },
  opts = {},
  keys = {
    { '<leader>At', ':Automator toggle<CR>', desc = 'Toggle Automator UI' },
    { '<leader>Aa', ':Automator apply<CR>', desc = 'Apply fix' },
    { '<leader>AA', ':Automator apply_all<CR>', desc = 'Apply fix to all' },
    { '<leader>Ad', ':Automator diagnostics<CR>', desc = 'Import diagnostics' },
    { '<leader>Ae', ':Automator errors<CR>', desc = 'Import errors' },
    { '<leader>Aw', ':Automator warnings<CR>', desc = 'Import warnings' },
    { '<leader>Ai', ':Automator infos<CR>', desc = 'Import infos' },
    { '<leader>An', ':Automator next<CR>', desc = 'Next location to fix' },
    { '<leader>Ap', ':Automator prev<CR>', desc = 'Prev location to fix' },
    { '<leader>Aq', ':Automator quickfix<CR>', desc = 'Import quickfix list' },
    { '<leader>Af', ':Automator toggle_file_mode<CR>', desc = 'Toggle file mode' },
    { '<leader>Ac', ':Automator insert_code_action<CR>', desc = 'Insert Code Action' },
    { '<leader>As', ':Automator stop<CR>', desc = 'Stop' },
    { '<leader>se', ':Automator pick errors<CR>', desc = 'Workspace errors' },
    { '<leader>sw', ':Automator pick warnings<CR>', desc = 'Workspace warnings' },
    { '<leader>sd', ':Automator pick diagnostics<CR>', desc = 'Workspace diagnostics' },
    { '<leader>sD', ':Automator pick file-diagnostics<CR>', desc = 'File diagnostics' },
    { '<leader>sE', ':Automator pick file-errors<CR>', desc = 'File errors' },
    { '<leader>sW', ':Automator pick file-warnings<CR>', desc = 'File warnings' },
    { '<leader>sq', ':Automator pick quickfix<CR>', desc = 'Quickfix list' },
    { '<leader>sQ', ':Automator pick file-quickfix<CR>', desc = 'File Quickfix list' },
    { '<leader>sr', ':Automator resume_pick<CR>', desc = 'Resume pick' },
  },
}
